name: Deploy Sample Site

on:
  push:
    branches: [ main ]

jobs:
  deploy-sample-site:
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v2

      # sets up .NET Core SDK 3.1
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: dotnet publish
        run: dotnet publish samples/wasm/Sample.Wasm.csproj -c:Release -o:release -p:GHPages=true --nologo

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
