# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      PRERELEASE: true
      REPOSITORY_URL: https://github.com/${{ github.repository }}.git
      PROJECT_URL: https://github.com/${{ github.repository }}
      BUILD_NUMBER: ${{ github.run_number }}
      COMMIT_SHA: ${{ github.sha }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.8.20417.9
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration Release --no-restore --nologo

    - name: dotnet pack
      run: dotnet pack -c Release -o dist --no-restore --no-build --nologo

    - name: dotnet nuget push (github)
      run: dotnet nuget push "./dist/*.nupkg" --skip-duplicate

    - name: dotnet nuget push (nuget)
      run: dotnet nuget push "./dist/*.nupkg" --skip-duplicate --source "nuget.org" --api-key ${{secrets.NUGET_API_KEY}}

#    - name: nuget push
#      run: nuget push .\dist\*.nupkg -Source "GPR" -SkipDuplicate
#
# publish:
#   runs-on: ubuntu-latest
#   if: github.ref == 'refs/heads/master'
