name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.8.20417.9
  
    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration Release --no-restore

    - name: dotnet pack
      run: dotnet pack -c Release -o dist

    - name: setup nuget
      uses: warrenbuckley/Setup-Nuget@v1

    - name: nuget sources add
      run: nuget sources add -name "GPR" -Source "https://nuget.pkg.github.com/${{ github.actor }}/index.json" -Username ${{ github.actor }} -Password ${{ secrets.GITHUB_TOKEN }}

    - name: nuget push
      run: nuget push .\dist\*.nupkg -Source "GPR" -SkipDuplicate

# publish:
#   runs-on: ubuntu-latest
#   if: github.ref == 'refs/heads/master'
